### ISSUE TITLE
TestApplication infinite loop

### ISSUE THREAD

**Issue by MrMazur** [Luigifan/DiscordSharp#1]
Hey there.

Just a side note, you may not want to display bad practices like "while (true);" in example applications. Consider reworking that example to use a waithandle. I was a bit terrified when I noticed the testapp was consuming 100% of one core, but it wasn't difficult to pinpoint the culprit after checking out the code.

Aside of that, this is some fine work, this API is very easy to work with. My discord bot based on your API hovers around 7mb memory usage and is almost always at 0% cpu usage. :+1:

**Comment by suicvne** [comment]
yeah it's honestly just temporarily/placeholder until I have enough time to properly do it. thank you though :D

**Comment by suicvne** [comment]
I actually found out that by just starting an empty `System.Windows.Forms.Application` and not providing a form, you will get a similar effect. In the meantime I will be learning WaitHandles and such..they look like a better solution to this.

Until then though, i've updated my example application to use the Forms method (e7c3fa1d3a4dfef8938404196b2d3bf2094e0ac5)

![2015-10-01 15_41_44-task manager](https://cloud.githubusercontent.com/assets/861492/10231834/f630b75c-6852-11e5-884d-74e14f1e83ce.png)

Thank you for this!
