### ISSUE TITLE
401 on Connect

### ISSUE THREAD

**Issue by EmptyKeys** [Luigifan/DiscordSharp#20]
Hi, every time I call Connect method, I got 401 - Unauthorized response code. Any idea why?

**Comment by suicvne** [comment]
How are you signing in? Is this a bot account?

**Comment by EmptyKeys** [comment]
No, testing it on your DiscordGUI example. So normal account.

**Comment by suicvne** [comment]
That example is outdated. I wouldn't use that.
You could check out this custom client i wrote in WPF if you're looking for a GUI example: https://github.com/Luigifan/WPFDiscordSharp

It's meant for normal clients (so not bots) and behaves like a client vs. a bot.

**Comment by EmptyKeys** [comment]
Same problem, 401 on Connect. Even simple code with just SendLoginRequest() and Connect() fails on 401. SendLoginRequest returns null and Connect fails in WebWrapper.

**Comment by EmptyKeys** [comment]
OK, the problem is implementation of GetGatewayUrl method in DiscordClient class. Testing UnauthorizedAccessException exception is useless there, because 401 is eaten by another exception (Object reference not set to an instance of an object).

**Comment by NorbiPeti** [comment]
And that error is returned because the token is null for some reason.

Edit: I think I found it. #22

**Comment by suicvne** [comment]
this should be fixed in nuget now.
