### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Jimmy062006** [Luigifan/DiscordSharp#25]
Hi there I'm getting Out of Memory errors when using the NuGet package.

I think I've tracked it down to DiscordSharp.Logger eating all the memory could you maybe give some insight to this.

**Comment by suicvne** [comment]
yeah it literally logs everything.
i can add a toggle in dev branch to enable/disable logging but i won't be pushing it to nuget yet

how many servers is your bot on?

**Comment by Jimmy062006** [comment]
One.

Soon to be Three though.

**Comment by suicvne** [comment]
o.O that shouldn't be happening then

**Comment by Jimmy062006** [comment]
It's running in debug mode currently. I'm going to keep taking memory snapshots to see what it increasing. Currently though it looks like only the log's

**Comment by suicvne** [comment]
![image](https://cloud.githubusercontent.com/assets/861492/13904441/4441623e-ee77-11e5-9b9e-f7ea5bda363c.png)

**Comment by Jimmy062006** [comment]
![oom](https://cloud.githubusercontent.com/assets/4639349/13904451/22e3bdcc-ee99-11e5-8567-b40f19adab40.PNG)

This is where we are at currently :-)

**Comment by Jimmy062006** [comment]
As a side note it seems something is hard coded my websocketlog.txt has these lines.

`at DiscordSharp.DiscordClient.<Connect>b__233_5(Object sender, EventArgs e) in C:\Users\Mike\Documents\GitHub\DiscordSharp\DiscordSharp\DiscordClient.cs:line 1669`

My names not Mike :P

**Comment by suicvne** [comment]
It pulls from the pdb file auto generated.

**Comment by suicvne** [comment]
![image](https://cloud.githubusercontent.com/assets/861492/13904470/44c26612-ee78-11e5-83f1-09cf336b99ec.png)
This is what i'm seeing. it seems to top out around 40mb and I'd expect it to increase with say, more servers or after a long day of logging messages _and_ json events. Personally, I've never experienced any OOM issues (granted, I'm running 64-bit processor, 12gb of RAM. but even then: DiscordSharp is a 32bit dll at the moment and so is my test bot).

**Comment by suicvne** [comment]
![image](https://cloud.githubusercontent.com/assets/861492/13904483/83007964-ee78-11e5-92a0-3f90147545fd.png)
I dump logs when I'm done running my bot and these are the average sizes. However, I log as much as I can for debug information. 

![image](https://cloud.githubusercontent.com/assets/861492/13904489/afd372c0-ee78-11e5-85d0-5ebee597f40a.png)

**Comment by Jimmy062006** [comment]
Yeah. I've made some changes but it was after a few hours of running and seemed to happen when there was connection issues.

It's running now with some modified code and I've got a 64bit processor and 16Gb ram (or more lol) so I'm not sure whats going on there :-) All my bot does is run a timer pull a webpage with just a version string on it and posts if the new version is larger.

**Comment by suicvne** [comment]
Interesting. Well, I can add an option in the client constructor to disable logging at least :)

**Comment by Jimmy062006** [comment]
If that is what is causing the issue then yes that would be good

**Comment by Jimmy062006** [comment]
I also don't have a logs folder I take it that's something you've coded in

**Comment by suicvne** [comment]
Yes, that's something that I've included on my bot's side

``` csharp
public void Cleanup()
        {
            if (client.GetTextClientLogger.EnableLogging)
            {
                if (!Directory.Exists("logs"))
                    Directory.CreateDirectory("logs");

                var date = DateTime.Now;
                string mmddyy = $"{date.Month}-{date.Day}-{date.Year}";
                if (!Directory.Exists("logs/" + mmddyy))
                    Directory.CreateDirectory("logs/" + mmddyy);

                int levels = (int)(MessageLevel.Debug & MessageLevel.Error & MessageLevel.Critical & MessageLevel.Warning);

                client.GetTextClientLogger.Save($"logs/{mmddyy}/{date.Month}-{date.Day}-{date.Year} {date.Hour}-{date.Minute}-{date.Second}.log", (MessageLevel)levels);
            }
        }
```

The `EnableLogging` property is new in this commit i'm about to push out to dev.

**Comment by Jimmy062006** [comment]
After tidying code up a little this issue seem's to have gone.

**Comment by suicvne** [comment]
👌

**Comment by ghost** [comment]
This is still an issue, the logger does eat gigabytes (never cleans up the log list) - but DiscordMember, and DiscordRole are also culprits. Running multiple GetServerList() and GetChannelList() cause memory leaks.

**Comment by suicvne** [comment]
you shouldn't be running those methods yourself
