### ISSUE TITLE
DiscordClient IsBotAccount field is always false

### ISSUE THREAD

**Issue by lzrp** [Luigifan/DiscordSharp#27]
```
public DiscordClient(string tokenOverride = null, bool isBotAccount = false)
        {
            token = tokenOverride;
            **isBotAccount = IsBotAccount;**

            // more code
        }
```

Seems to me as a typo as it should be `IsBotAccount = isBotAccount`, since this way you are assigning a default (false) value to the supplied parameter variable. This way the bot never adds the appropriate values to auth headers.

**Comment by suicvne** [comment]
Yup, innocent typo. My bad :D
