### ISSUE TITLE
Weird 4002 errors since today (05-04-2016)

### ISSUE THREAD

**Issue by Xeltor** [Luigifan/DiscordSharp#31]
During the login of my bot it all of a sudden has started giving the following error.

Console log:

> [19:17:24][INFO]  Attempting login..
> [19:17:24][INFO]  Logged in.
> [19:17:28][ERROR] Socket Closed! Code: 4002. Reason: Error while decoding payload.. Clear: True.
> [19:17:28][INFO]  Waiting 6 seconds to reconnect..
> [19:17:28][INFO]  Connected! User: Bot

Websocket log file:

> 05-Apr-16 20:40:44|Fatal|WebSocket.processException|WebSocketSharp.WebSocketException: The 'Payload Data' of a frame cannot be read from the data source.
>                             at WebSocketSharp.WebSocketFrame.read(Byte[] header, Stream stream, Boolean unmask)
>                             at WebSocketSharp.WebSocketFrame.<>c__DisplayClass7.<ReadAsync>b__6(Byte[] header)
>                             at WebSocketSharp.Ext.<>c__DisplayClass6.<ReadBytesAsync>b__5(IAsyncResult ar)

Might any of you know what may be causing this?

**Comment by suicvne** [comment]
Dev or nuget/master?

**Comment by suicvne** [comment]
Just got confirmation that Discord is shutting down all old Gateways. Unfortunately that means that the current nuget version is borked. Dev has some v4 support (thank god I did that) and should be able to connect just fine. I'm not sure when I'll have a chance to push to NuGet

**Comment by Xeltor** [comment]
i will switch to dev for now and see if that will get it back online, thanks for the quick reply :+1:

**Comment by suicvne** [comment]
no problemo 👌

**Comment by Xeltor** [comment]
Yup, compiling the dev version seems to have fixed the problem, thanks!

**Comment by NebriBlackwing** [comment]
Is it possible to set up the development branch as a git module in my own solution? I realize that comes with it's own risks, but it may be an easier and faster way to distribute updates than nuget. 

Don't get me wrong I love the fact that @Luigifan is supporting nuget, it's the simple easy way, but my project is currently stalled until it can be updated. 

Thanks @Luigifan for taking the time to look into this, I am looking forward to an update when your able to roll it out!

**Comment by suicvne** [comment]
git does support some kind of submodules system but I have no idea how that works or if you can even specify a specific branch for that. Appveyor spits out per commit builds; if you go to releases you can check it out. I would've had a build pushed out today but alas, life, school, etc.

**Comment by suicvne** [comment]
Plus not to mention I'm not entirely sure if these latest commits are stable. For example, everything I've tested runs fine on Win7, Win10 and Ubuntu. However, I have another user who can't even get it to run at all on Windows

**Comment by suicvne** [comment]
Safe to close? Re-open by request :D
