### ISSUE TITLE
WebRequest Error

### ISSUE THREAD

**Issue by KodyPrograms** [Luigifan/DiscordSharp#32]
"4/6/2016 5:25:04 PM|Error|WebSocket.Send|The WebSocket connection has already been closed."

Been getting this error. Using the DiscordSharp provided here and the "Getting Started bot" from NaamloosDT. This is the error I get after I cleaned up the code a little and such. Had to import a new .dll of DiscordSharp because the default one with the getting started bot wasn't working correct. 

Any help with this?

**Comment by suicvne** [comment]
Is this on latest dev? What are you doing with the bot? Last thing it did?

**Comment by KodyPrograms** [comment]
Yes it is the latest dev just downloaded it today. Just a simple chat bot with commands and such gonna do more things when i get the basic framework for this done.

**Comment by KodyPrograms** [comment]
I also tried to run the commands test and it gave me some webrequest error as well.

**Comment by suicvne** [comment]
was there a specific thing the bot did before receiving this error?

**Comment by suicvne** [comment]
yeah commandstest is borked

**Comment by KodyPrograms** [comment]
No, all it did was login said it connected. then crashed.

**Comment by suicvne** [comment]
Okay interesting. What OS is this on?

**Comment by KodyPrograms** [comment]
Windows 10. Do you want to teamview or something so I can show you exactly what's going down.

**Comment by suicvne** [comment]
I can't right now but at another time I'd like to. Recently, Discord changed some Gateway things and its been flaky for some users (but I've been able to run fine on Win10 and Ubuntu).

**Comment by KodyPrograms** [comment]
Can you send me over your source code of a working version so I can have a looky at it?

**Comment by suicvne** [comment]
You don't happen to have any messaging sending being done in the on connect event do you? One other thing Discord started doing is guild chunking which kinda destroys any logic in the on connect. Most recent Dev commits implement a 3 second timeout before actually triggering the connected event.

**Comment by suicvne** [comment]
One other suggestion I can make because you're on Windows 10 (and you're feeling brave) 
1. Open up DiscordClient.cs
2. Go to the connect method
3. change the line `ws = new WebSocketSharpSocket(` to `ws = new NetWebSocket(` keeping the params. This uses the .Net built in websocket as a back end and is only available on Win8+. Please let me know.

**Comment by suicvne** [comment]
Checkout the DiscordSharpTestApplication. LuigibotMain.cs

**Comment by KodyPrograms** [comment]
So i figured out the error happens when I try to change the current game it is playing. 

EDIT : Nevermind it just straight up isn't working

**Comment by KodyPrograms** [comment]
As far as changing it to NetWebSocket. It doesn't seem to know what that is.

**Comment by KodyPrograms** [comment]
Do you mind sending me the source code of your working one?

**Comment by Sutakko** [comment]
I had same error. Just use the dev branch and your good to go!

**Comment by suicvne** [comment]
kody, check the DiscordSharpTestApplication in the repo.

**Comment by suicvne** [comment]
Also it sounds like you're not on Dev branch

**Comment by KodyPrograms** [comment]
What is the Dev branch?

**Comment by KodyPrograms** [comment]
and i did check out the DiscordSharpTestApplication that one also crashed for me

Errors and such here 
https://i.gyazo.com/7645f06d0da6e068adbb0618ea71df8b.png

**Comment by suicvne** [comment]
![image](https://cloud.githubusercontent.com/assets/861492/14371026/4e2c575c-fd01-11e5-91e2-fd0d703e176a.png)

Please try out dev branch and let me know.

**Comment by crunchyintheory** [comment]
I am also having the exact same area. Trying dev branch now...

**Comment by suicvne** [comment]
Like I said, Discord changed a bunch of stuff internally. More than likely your `Connected` event logic will be destroyed because of it. :/

**Comment by crunchyintheory** [comment]
I'm using the current latest nuGet version. client.Connected does not trigger, and to my knowledge none of the other ones do. The bot essentially signs in to Discord then sits and does nothing. I will push my latest source to my repo http://github.com/SpawnerSwarm/SwarmBot so you can see how it looks. Good to know I'm not the only one suffering from this.

**Comment by crunchyintheory** [comment]
I'm also no longer getting an error message; it just doesn't do anything.

**Comment by KodyPrograms** [comment]
I fixed it basically I just replaced the DiscordSharp.dll with the one from the dev version. Fixed it right away

**Comment by rittbys** [comment]
I wasn't able to get the dev branch to build? @kodyisking what method did you use?

**Comment by crunchyintheory** [comment]
In the process of capitalizing every single reference in my code ;_;

**Comment by crunchyintheory** [comment]
Dev branch seems to fix it. I had to reformat a large portion of my code but it works! Great job, @Luigifan !

**Comment by suicvne** [comment]
Sorry about that guys :( but glad to see this is fixed. I'll be pushing to NuGet this weekend.
