### ISSUE TITLE
Unable to connect and read/send messages.

### ISSUE THREAD

**Issue by Krognol** [Luigifan/DiscordSharp#36]
The `Connected` event doesn't write anything to the console after starting. I changed `client.ClientPrivateInformation.email` and `client.ClientPrivateInformation.password` to `client.ClientPrivateInformation.Email` and `client.ClientPrivateInformation.Password`.  It used to work just fine, not sure what changed. I have version `0.6.0.7-rc1` according to NuGet.

**Comment by suicvne** [comment]
Try latest Dev branch build

**Comment by Krognol** [comment]
Yup, that fixed it! Thanks!
