### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by bl89** [Luigifan/DiscordSharp#39]
"System.TypeLoadException was unhandled
Message: An unhandled exception of type 'System.TypeLoadException' occurred in mscorlib.dll
Additional information: Could not load type 'DiscordSharp.DiscordClient' from assembly 'DiscordSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."

I get this error whenever I compile. I could have overlooked something but I have no idea why this is happening. I am using version 0.6.2-rc1.

**Comment by suicvne** [comment]
compiling just your bot? that's really..weird.

**Comment by bl89** [comment]
Yeah. It's nothing special. I can show you the source if you want it

**Comment by bl89** [comment]
Nevermind, solved the issue. Looks like you have to use NuGet to install DiscordSharp, compile **before** you make your bot, so that it auto-generates AssemblyInfo etc and then make your bot.

**Comment by suicvne** [comment]
That's weird. I've never had that happen to me before but, glad to see you got this resolved!
