### ISSUE TITLE
UserisSpeaking event

### ISSUE THREAD

**Issue by LynnAU** [Luigifan/DiscordSharp#4]
More of a suggestion than an issue since this event doesn't seem to be documented nor listed anywhere.

According to `Discord.Net`'s documentation. It lists,

<table>
    <th>Event Name</th>
    <th>EventArgs</th>
    <th>Description</th>
    <tr>
        <td>UserIsSpeaking Updated</td>
        <td>UserEventArgs</td>
        <td>Called when a user’s voice state changes. (Speaking\Not Speaking)</td>
    </tr>
</table>

But has no example using it. Does `DiscordSharp` have such an event?

I'm writing an application that alerts the user when somebody in a voice channel starts speaking.

**Comment by LynnAU** [comment]
Its seems like the [DiscordSharp/Voice/DiscordVoiceClient.cs#L68](https://github.com/Luigifan/DiscordSharp/blob/master/DiscordSharp/Voice/DiscordVoiceClient.cs#L68) needs a new `else if` to the `int` of 5 which is the speaking ID and simply needs to call the event as shown by the `Discord.Net` example [src/Discord.Net.Audio/Net/VoiceWebSocket.cs#L442-L447](https://github.com/RogueException/Discord.Net/blob/c1f24d164b20765e2567ced8ebdec806d741e906/src/Discord.Net.Audio/Net/VoiceWebSocket.cs#L442-L447)

**Comment by suicvne** [comment]
It is something like that (what you said about the `else if`). However,
voice is in super early progress right now. When I have a moment I'll add
that in real quick (the main client will wrap the voice client events) but
I can't guarantee the stability of it.

**Comment by suicvne** [comment]
Implemented and (hopefully) working in fdf489d1fe5093df953e4eee92129c67434a82c0
