### ISSUE TITLE
Github version different to Nuget version

### ISSUE THREAD

**Issue by bl89** [Luigifan/DiscordSharp#40]
I have been using DiscordSharp 0.6.2-rc1 from NuGet and was talking to another bot dev who had a GitHub release (version 0.6.0.50-dev). His libraries contained a DiscordRole class, while the NuGet version doesn't. I'm not sure if it was removed in the newer NuGet and GitHub version or was not included in one.

**Comment by suicvne** [comment]
I fail to see how the two versions being different is an issue. My repo has two seperate branches: master and dev. Master containing the latest version that's on NuGet and dev containing the latest work I've done. 

The class was not removed. Import `DiscordSharp.Objects`.

**Comment by bl89** [comment]
Oh right, thanks. I am just a bit silly and didn't notice the dev branch.

**Comment by suicvne** [comment]
:ok_hand:
