### ISSUE TITLE
Event for Serverlist

### ISSUE THREAD

**Issue by nick-strohm** [Luigifan/DiscordSharp#42]
Hey, it would be awesome, if you could make an event that fires when the serverlist is fully received. I have some functions in the connected event, that needs the fully serverlist.

Best regards

**Comment by suicvne** [comment]
That's what I was trying to do actually: artificially delay the firing of READY until all servers are retrieved

The easy solution would be checking if all unavailable servers are available each time the proper event fires, but then what about when an actual offline server is introduced? The bot will be in limbo.

**Comment by nick-strohm** [comment]
So the easiest would be, that Discord just fires an event

**Comment by suicvne** [comment]
Yes which I wish they'd do. Ultimately, their servers know how many servers I'm a part of and what's properly online and whatnot. But alas, that probably won't come.

Something more practical than that would be going back to sending guilds in the READY for small bots, like ours, which are in only a few servers. But alas, something else that won't happen.
