### ISSUE TITLE
Usernames are not updated while running

### ISSUE THREAD

**Issue by Naamloos** [Luigifan/DiscordSharp#44]
If a user or admin updates a nickname, the bot still uses the nickname that user had at boot (or first time calling code, not sure)

example:
![image](https://cloud.githubusercontent.com/assets/12187179/14962550/ad124ea0-109f-11e6-9242-fa6677ee352a.png)

**Comment by suicvne** [comment]
`Succ`
Lemme look into it.

**Comment by suicvne** [comment]
Confirmed. Fixing.

**Comment by suicvne** [comment]
![image](https://cloud.githubusercontent.com/assets/861492/14967502/b499c370-1085-11e6-8a1c-96af58ec896e.png)

**Comment by Naamloos** [comment]
thanks for fixing.

**Comment by Naamloos** [comment]
.* notices light theme *
