### ISSUE TITLE
DiscordClient.Connected event handler does not fire

### ISSUE THREAD

**Issue by sophec** [Luigifan/DiscordSharp#52]
Not sure if it's my app, but all of my event handlers work perfectly fine - except for this one:

``` c#
DiscordClient client = new DiscordClient(token, true);
client.Connected += (sender, e) => {
    // code in here never runs
};
```

I have tried replacing it with other things, other forms of things, I've tried debugging it, but it never fires.

**Comment by suicvne** [comment]
did you call `client.Connect();` ?

**Comment by sophec** [comment]
@Luigifan yessir, all the way at the bottom after defining all my handlers. Not sure why this one will not work. As you can see [here](https://gist.github.com/WillEccles/c813f4e79f54a7facd0d9df8907d6e0f#file-main-cs-L18), I called `client.Connect();`, but nothing happens. The handler will never be called.

**Comment by suicvne** [comment]
I can't say I can reproduce. :/

**Comment by sophec** [comment]
@Luigifan I will do some more testing when I get home and let you know how it goes, but I was not able to fix the problem.

**Comment by Akuba-** [comment]
Not sure if I should open a new issue.

I actually have the same issue, but only when I run it on my linux server using mono.
It works fine on my windows pc's, but not on my linux one.

**Comment by sophec** [comment]
@Akuba- I'm running Windows here, so it isn't an OS-dependent problem.

**Comment by sophec** [comment]
Closing out of old age and lack of reproducibility.
