### ISSUE TITLE
Audio Help!?

### ISSUE THREAD

**Issue by PoofImaFox** [Luigifan/DiscordSharp#62]
_Sorry if I am putting this in the wrong spot_
Well anyway i need help streaming an MP3 file through the client I can't find 
ANY documentation anywhere. Thank you!

**Comment by DuaneTheDev** [comment]
DiscordSharp/DiscordSharpTestApplication/Modules/Voice.cs
https://github.com/Luigifan/DiscordSharp/blob/master/DiscordSharpTestApplication/Modules/Voice.cs

If you do follow that code, you'll need the opus.dll and libsodium.dll within the same folder.

**Comment by PoofImaFox** [comment]
Thanks btw, Is A LOT late. but thanks.
