### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by Blizzardo1** [Luigifan/DiscordSharp#63]
Is there a possibility of Two-Factor-Authentication?

**Comment by arqunis** [comment]
No, the devs said about not automating 2fa nor `/api/login` at all, if you want a login like approach just use a token. _normal client_ `ctrl+shift+i` -> console tab -> type localStorage.token -> copy the token _without the two double quotes surounding it_ or if it's a bot account just go to the dev page and copy it there

**Comment by arqunis** [comment]
although jake said that's it's fine to automate them for a lib but then again you're risking the users getting banned

**Comment by Blizzardo1** [comment]
Thanks, I'll try that.
