### ISSUE TITLE
Sending emoji through code causes error.

### ISSUE THREAD

**Issue by suicvne** [Luigifan/DiscordSharp#7]
(Reported by `Kazurik` on Discord)

The following example: https://gist.github.com/davidneumann/6e5d49dd3cd82e0b0603
Will fail and give the following error:
`The request was aborted: The request was canceled.`

Could be an `HttpWebRequest` bug.

**Comment by suicvne** [comment]
More info: 

"Commit cc1b204 is the comit that first triggers this"

**Comment by suicvne** [comment]
Potential workaround in dd41ca929aed832278ffce52e962d43a0a4cf2d6. Will keep open.

**Comment by suicvne** [comment]
Closing for now as no one else has complained of this issue.

**Comment by ghost** [comment]
I had a problem like this except with discord.py. It might be because the console doesn't support unicode. There's a way to get the console to support it though, try and google it.

**Comment by suicvne** [comment]
cmd.exe console will just display Unicode characters it doesn't support as boxes. With Python it just crashes I think. But yeah I don't think anyone else has had any other problems with this :)
