### ISSUE TITLE
Logging in with bot token?

### ISSUE THREAD

**Issue by CoderReece** [Luigifan/DiscordSharp#71]
I know this is dead but discord.net isn't compatible with something of mine and this works really well as a temp work around.. But yeah how do i login with a bot token?

**Comment by CoderReece** [comment]
Woops i found it, I haven't used this in a while so i had completely forgotten where everything is :S I hope this project gets revived in the future as not everyone wants or can go the async way even if its better.

**Comment by suicvne** [comment]
https://github.com/NaamloosDT/DSharpPlus

**Comment by CoderReece** [comment]
That's "discord.net" this api works much better for what i'm trying to achieve and i'm well aware DSharpPlus is better and not dead but its not what i need.
