### ISSUE TITLE
Set a Status on account

### ISSUE THREAD

**Issue by AndreZila01** [Luigifan/DiscordSharp#75]
Hey everyone i would like understand how i can set a status on my account.
I try use this command `await discord.UpdateStatusAsync(new DiscordActivity("!help", DSharpPlus.Entities.ActivityType.Playing), UserStatus.DoNotDisturb);`, but he return this:
System.NullReferenceException: 'Object reference not set to an instance of an object.'.

Is possible change status of account?

**Comment by suicvne** [comment]
<img width="918" alt="Screen Shot 2022-08-30 at 9 01 03 AM" src="https://user-images.githubusercontent.com/861492/187443419-90097f1a-0028-4f42-b58e-4dc1e08b2fb8.png">
