### ISSUE TITLE
DiscordClient.GetVoiceClient() NullReferenceException

### ISSUE THREAD

**Issue by AshkoreDracson** [Luigifan/DiscordSharp#8]
Here is my snippet code

``` cs
if (voiceChannels.Count > 0)
{
    client.ConnectToVoiceChannel(voiceChannels[0]);

    Thread.Sleep(1000);

    DiscordVoiceClient vc = client.GetVoiceClient();
    if (vc != null)
    {
        WriteLine("WAV sent");
        vc.SendWav(@"C:\Users\Adrien\gaben.wav");
    }
    else
    {
        WriteLine("WAV not sent");
        client.DisconnectFromVoice();
    }
}
```

It throws a NullReferenceException when trying to do `DiscordVoiceClient vc = GetVoiceClient()`, more specifically, I have a tiny stacktrace that the exception is thrown by line 1337 from `DiscordClient.cs`

Because of this, I cannot use in any way the voice client.

**Comment by suicvne** [comment]
The voice client is not complete and will not be complete for a long time.
